### PR TITLE
Price impact warning not working properly

### LINKED ISSUE #2445: Price impact warning not working properly

### PR DESCRIPTION
**Pull request by kkosiorowska**
Closes #2445 

This PR fixes issue with loading price impact. Issue was connected that not all of assts have recentPrices. The changes allow the creation of a price point when it is empty. 

**UI**

Before
Screenshot 2022-10-17 at 16 50 32

After
Screenshot 2022-10-18 at 08 56

Screenshot 2022-10-18 at 08 56 37

**To Test**
- [ ] go to swap and check price impact indicator woking properly

### CODE REVIEW

File: background/redux-slices/utils/0x-swap-utils.ts [hunk 1]
```diff
@@ -38,16 +44,44 @@ export type PriceDetails = {
...
 }
 
-export function getAssetAmount(
+export async function getAssetPricePoint(
+  asset: SmartContractFungibleAsset | FungibleAsset,
+  assets: AssetsState,
+  network: EVMNetwork
+): Promise<PricePoint> {
+  const assetPricesNetworks = assets
+    .filter(
```
Comment (greg-nagy) [inline background/redux-slices/utils/0x-swap-utils.ts:53]: non blocking comment: this will return all the addresses for the symbol on all networks. This won't cause any issues later, because coingecko api will filter out the token addresses that are not valid on a given network.

**Review by greg-nagy — APPROVED** [review]
Quick fix which works well! 

Nice ✨

File: background/lib/prices.ts [hunk 2]
```diff
@@ -162,3 +164,26 @@ export async function getTokenPrices(
...
+
+/*
+ * Get a Price Point for asset to USD.
+ */
+export function getPricePoint(
+  asset: SmartContractFungibleAsset | FungibleAsset,
+  unitPricePoint: UnitPricePoint<FungibleAsset>
+): PricePoint {
+  return {
+    pair: [asset, USD],
```
Comment (Shadowfiend) [inline background/lib/prices.ts:176]: Please don't hardcode USD 🙏 We've done a tremendous amount of work to make almost all computations based on the user's preferred local currency, despite not having exposed the preference quite yet (due in part to some stragglers).

If price impact requires USD specifically, let's make sure the function name is clear that it is specifically for USD.
