### PR TITLE
📈 Fix currency value for gas fee estimation

### LINKED ISSUE #1769: We are massively overquoting gas fees
On an ERC20 send:

- I'm quoted 215 Gwei on SEND page
- I'm quotes $15 on txn signature page
- Paid fee = 0.011318892440457976 MATIC ($0.01) (https://polygonscan.com/tx/0xe0aafc9b5858133ed5444c52f97c07788d001b50cdc756f50cd1ec160a4901ea)

Screen Shot 2022-07-07 at 9 10 50 PM

Screen Shot 2022-07-07 at 9 11 29 PM

...

On a Swap:

- I'm quoted $20 on the main SWAP page
- I'm quoted $26 on txn signature page 
- Actual gas is $0.01 https://polygonscan.com/tx/0xd5e4eb335b59f7912d869736572cd9bcd10ae2cb5a88ff8f8d3a6b047b1141a4 

Screen Shot 2022-07-07 at 9 17 53 PM

Screen Shot 2022-07-07 at 9 18 05 PM

My conjecture on what may be happening:

- Our $usd quotes are based on ETH rather than MATIC prices

### PR DESCRIPTION
**Pull request by henryboldi**
Matic
matic
Ethereum
eth-mainnet

Closes #1769

⚠️ Planning to write a proper description, but feel free to review it now

### CODE REVIEW

File: background/redux-slices/selectors/accountsSelectors.ts [hunk 1]
```diff
@@ -208,9 +208,13 @@ export const selectAccountAndTimestampedActivities = createSelector(
...
   getAssetsState,
   (state) => selectMainCurrencySymbol(state),
-  (assets, mainCurrencySymbol) => {
-    // TODO Support multi-network base assets.
-    return selectAssetPricePoint(assets, "ETH", mainCurrencySymbol)
+  selectCurrentNetwork,
+  (assets, mainCurrencySymbol, currentNetwork) => {
+    return selectAssetPricePoint(
+      assets,
+      currentNetwork.baseAsset.symbol,
```
Comment (0xDaedalus) [inline background/redux-slices/selectors/accountsSelectors.ts:215]: I'm not sure this will work if the wallet is connected to `Ethereum` but signing a transaction from a dapp connected to `Polygon`

Comment (0xDaedalus) [reply background/redux-slices/selectors/accountsSelectors.ts:215]: Yeah just tested and this does seem to be the case - i think maybe the answer here is to have the `selectMainCurrencyPricePoint` selector take an optional baseAsset as an argument

Comment (henryboldi) [reply background/redux-slices/selectors/accountsSelectors.ts:215]: Excellent point. Thank you! Fix incoming

**Review by 0xDaedalus — DISMISSED** [review]
LGTM just need linter passing

**Review by 0xDaedalus — APPROVED** [review]

**Comment by greg-nagy** [comment]
I think we probably shouldn't have done this 

CleanShot 2022-07-08 at 20 29 08
CleanShot 2022-07-08 at 20 29 45


But my understanding of the decisions about what corners are ok to cut here might be not full.

**Comment by henryboldi** [comment]
You're looking at it with the new gas settings turned off though. This PR is for the gas new settings, @greg-nagy

**Comment by henryboldi** [comment]
Also, @greg-nagy, that deprecated screen you're looking at is fixed in https://github.com/tallycash/extension/pull/1764, but we decided to deprioritize it
