### PR TITLE
Fix activity item styling

### LINKED ISSUE #2080: Fix activity item styling
Fix how the activity list item is looking when the token name is long

image

### PR DESCRIPTION
**Pull request by kkosiorowska**
Closes #2080 

This PR fixes the issue how the activity list item is looking when the token name is long.

**Changes**

When the name or amount is too long the name should jump to the next line. The address shouldn't jump to the next line.

**UI**

Before

Screenshot 2022-09-06 at 20 21 07

After

Screenshot 2022-09-06 at 20 21 07
Screenshot 2022-09-06 at 20 20 30
Screenshot 2022-09-06 at 20 19 48

**To Test**

Go to the activity list and check how the activity list item looks.  Check a few variants: 
- [ ] When name is too long
- [ ] When amount is too long
- [ ] Short amount and short name

### CODE REVIEW

File: ui/components/Wallet/WalletActivityListItem.tsx [hunk 1]
```diff
@@ -294,6 +296,9 @@ export default function WalletActivityListItem(props: Props): ReactElement {
             // For Infinite text in token approvals.
             text-transform: none;
           }
+          .name {
+            white-space: nowrap;
```
Comment (jagodarybacka) [inline ui/components/Wallet/WalletActivityListItem.tsx:300]: Let's add top padding to align bottom text line of value and currency name
Before Screenshot 2022-09-07 at 11 59 22
After Screenshot 2022-09-07 at 12 01 51


```suggestion
            white-space: nowrap;
            padding-top: 3px;
```

**Review by jagodarybacka — COMMENTED** [review]
One small thing and we are ready to go 😉

**Review by jagodarybacka — APPROVED** [review]
LGTM 🎊
