### PR TITLE
😷 Dapp Distancing: Notify dApps when a user disconnects

### LINKED ISSUE #489: Dispatch all the events defined in EIP-1193 in `TallyWindowProvider`

### LINKED ISSUE #608: [Bug]: When I disconnect from a dapp, I need to refresh the page before my account disappears from dapp UI
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I wanted to disconnect from saddle and see that immediately reflected in the saddle UI ... 

### What did not work?

... after I disconnected (~20 secs at video), the saddle nav displayed that my wallet was still connected until I manually refreshed (~33 secs):

https://user-images.githubusercontent.com/7005061/145884597-9ceca3da-eacc-4d1f-95cf-b21aed7952a4.mov

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by greg-nagy**
# PURRRpose

As a Degen 
I want to see dApp become disconnected when I revoke the permission in the wallet 
so that I know the dApps can not access my account anymore

# Demo
CleanShot 2021-12-22 at 17 23 17

Fixes #608, closes #489

### CODE REVIEW

File: background/services/provider-bridge/index.ts [hunk 1]
```diff
@@ -188,7 +188,7 @@ export default class ProviderBridgeService extends BaseService<Events> {
     })
   }
 
-  async notifyContentScriptsAboutAddressChange(newAddress: string) {
+  async notifyContentScriptsAboutAddressChange(newAddress?: string) {
```
Comment (henryboldi) [inline background/services/provider-bridge/index.ts:191]: `Missing return type on function` 🙃

**Review by henryboldi — APPROVED** [review]
Very nice 🤌
