### PR TITLE
Fix meshswap dapp connection

### LINKED ISSUE #1761: Polygon | Meshswap - Can't connect wallet (us or them?)
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/tree/polygon-qa-3

### **Reproduction Steps:**

1. Attempt to connect Tally using Meta Mask (no inject or Tally option)

### **Expected Result:**
Connected! 

### **Actual Result:**
image

### PR DESCRIPTION
**Pull request by greg-nagy**
- adding isWeb3 flag to `window-provider`
- saving the chainId on the `window-provider` in case of `wallet_switchEthereumChain` || `wallet_addEthereumChain`

Note: on the initial connection, a `wrong network` error will be shown. 
Fixing this would require white-labeling meshswap which is probably not a good idea. 
This behavior is identical with MM. 

Closes #1761

### CODE REVIEW

File: window-provider/index.ts [hunk 1]
```diff
@@ -33,6 +33,8 @@ export default class TallyWindowProvider extends EventEmitter {
 
   isMetaMask = false
 
+  isWeb3 = true
```
Comment (henryboldi) [inline window-provider/index.ts:36]: > for some reason meshswap checks for this
flag before willing to work with any injected
provider

Curious!

**Review by henryboldi — APPROVED** [review]
Looks good 💪
