### PR TITLE
Fix sending ETH on Optimism.

### LINKED ISSUE #2014: Can't send assets on Optimism
### What

Trying to send assets is redirecting user instead of setting up transaction

https://user-images.githubusercontent.com/20949277/186460581-6138f957-4385-42ec-b5e1-40b294641694.mov

### PR DESCRIPTION
**Pull request by 0xDaedalus**
Closes #2014 

This PR allows users to send ETH to other addresses through the extension.

Things Learned:
- [ETH is an ERC-20 token on Optimism](https://optimistic.etherscan.io/token/0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000)
- We were doing rollup fee estimation incorrectly - which was causing us to overestimate gas fees and prevented transfer ETH transactions from going through once we correctly identified it as a baseAsset.

### To Test
- [ ] Attempt to send ETH to an address on Optimism.

### CODE REVIEW

File: background/services/chain/index.ts [hunk 1]
```diff
@@ -823,11 +829,12 @@ export default class ChainService extends BaseService<Events> {
 
   async estimateL1RollupFee(
     network: EVMNetwork,
-    input: string | null | undefined
+    transaction: UnsignedTransaction
```
Comment (jagodarybacka) [inline background/services/chain/index.ts:832]: is there any place that is using this function and doesn't need to run `unsignedTransactionFromEVMTransaction(transactionRequest)` before passing it as this argument? 
If there isn't - maybe it's worth moving this `unsignedTransactionFromEVMTransaction` transformation to this function?

File: background/constants/currencies.ts [hunk 2]
```diff
@@ -25,6 +25,20 @@ export const ETH: FungibleAsset & CoinGeckoAsset & NetworkBaseAsset = {
   },
 }
 
+export const OPTIMISTIC_ETH: FungibleAsset & CoinGeckoAsset & NetworkBaseAsset =
+  {
```
Comment (jagodarybacka) [inline background/constants/currencies.ts:29]: base asset needs homeNetwork field
https://github.com/tallycash/extension/blob/send-eth-optimism/background/services/indexing/db.ts#L67
image

**Review by jagodarybacka — CHANGES_REQUESTED** [review]

File: background/constants/currencies.ts (hunk 2 above)
Comment (0xDaedalus) [reply background/constants/currencies.ts:29]: Hmmmmnn I was hoping to avoid changing the `NetworkBaseAsset` type any further - let me see if I find an alternative way to just adding it

File: background/services/indexing/db.ts [hunk 3]
```diff
@@ -61,7 +61,7 @@ export type CachedTokenList = TokenListCitation & {
  */
 function assetID(asset: AnyAsset): string {
   const id = `${asset.symbol}`
-  if (!("contractAddress" in asset)) {
+  if (!("contractAddress" in asset) || "coinType" in asset) {
```
Comment (0xDaedalus) [inline background/services/indexing/db.ts:64]: @Shadowfiend curious for your take on this

**Review by jagodarybacka — APPROVED** [review]
Sending ETH on OP is fixed 👑
