### PR TITLE
🤝 MM and Tally, two good friends when using uniswap

### LINKED ISSUE #2077: Default wallet feature is not working on Uniswap with MM
### What

MetaMask is always showing up on Uniswap despite TallyHo's default wallet setting

### PR DESCRIPTION
**Pull request by greg-nagy**
> 🇵🇱🤝🇭🇺 https://en.wikipedia.org/wiki/Pole_and_Hungarian_brothers_be

Fix logical error in wallet router whitelist elements should be || and not &&

Closes #2077

### CODE REVIEW

File: src/window-provider.ts [hunk 1]
```diff
@@ -123,8 +123,8 @@ Object.defineProperty(window, "ethereum", {
           // as a workaround we need to remove this list for uniswap so the actual provider change can work after reload.
           // The same is true for `galaxy.eco`
           if (
-            window.location.href.includes("app.uniswap.org") &&
-            window.location.href.includes("galaxy.eco") &&
+            (window.location.href.includes("app.uniswap.org") ||
+              window.location.href.includes("galaxy.eco")) &&
```
Comment (0xDaedalus) [inline src/window-provider.ts:127]:
```suggestion
              window.location.href.includes("galxe.com")) &&
```

**Review by 0xDaedalus — CHANGES_REQUESTED** [review]
One small change request

**Review by 0xDaedalus — APPROVED** [review]
Tested and looks good ✅
