### PR TITLE
Alarming Balances: Update balances when transactions are confirmed

### LINKED ISSUE #707: After dapp interaction (trade or deposit), resulting token balances don't update in Tally
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

Trade on Sushi for DAI ... doesn't show up after 10 mins / 40+ confirmations

Screen Shot 2021-12-16 at 7 00 19 PM

I reinstall the app and it shows up

Log into Yearn and deposit DAI into a Vault and get yvDAI back ... still shows 40 DAI in Tally and not new yvDAI

Screen Shot 2021-12-16 at 7 08 47 PM

Screen Shot 2021-12-16 at 7 09 10 PM

I reinstall app and it shows up again

Screen Shot 2021-12-16 at 7 14 33 PM

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Shadowfiend**
When transactions near the chain tip with a successful status are
seen, the indexing service now schedules a token balance lookup to
occur within 1 minute. This should ensure that any transactions that
affect balances update the balance in relatively short order, even if
we don't have enough insight into the transaction itself to locally
handle those updates.

~~Fixes~~ Refs #707 .

### CODE REVIEW

File: background/services/chain/utils.ts [hunk 1]
```diff
@@ -147,11 +148,16 @@ export function ethersTransactionFromSignedTransaction(
...
   receipt: EthersTransactionReceipt
-): AnyEVMTransaction {
+): ConfirmedEVMTransaction {
+  const gasUsed = receipt.gasUsed.toBigInt()
   return {
     ...transaction,
-    gasUsed: receipt.gasUsed.toBigInt(),
-    status: receipt.status,
+    gasUsed,
+    status:
```
Comment (mhluongo) [inline background/services/chain/utils.ts:156]: Right! Good catch.

**Review by mhluongo — APPROVED** [review]
Code looks good and I don't see any regressions, but note... this won't actually fix #707 if the resulting token balance change is a token that Alchemy doesn't balance check by default. To fix that, we need either local contract inference, balance checking by token list, or more aggressive use of `getAssetTransfers` (which is impaired by chain tip data ingestion issues)

**Comment by Shadowfiend** [comment]
> won't actually fix #707 if the resulting token balance change is a token that Alchemy doesn't balance check by default

Completely agree btw. This was meant to fix it for tokens the wallet is already monitoring, but not for new ones. Missed that 707 referred to both.
