### PR TITLE
Fix asset transfers

### LINKED ISSUE #1158: Wallet Balances Not Updating
ERC-20 Token and ETH balances are not correctly updating in the application.  It is likely that #1082, #1067, and #1109 are all related to this issue.  This issue is here to coordinate bug-hunting efforts to help us get to the root cause quicker.

# Related issues
- [x] #1067 
- [ ] #1082

### PR DESCRIPTION
**Pull request by greg-nagy**
# What

Created an alarm to check for transactions every minute. 
There is a ~5 minutes delay in transactions that we are picking up now, which is not ideal.

Also fixed the asset flow to add the assets from the history to the `assetsToTrack` list.

# Test
- revert #1755
- import a new wallet with a history 
- `tally/indexing > assetsToTrack` should be populated with all the assets
  - note: the UI will pick up the changes in the next minute or so 

🤔 Why is the UI not populated with all the assets on the first run?

Ref #1158

### CODE REVIEW

File: background/services/chain/index.ts [hunk 1]
```diff
@@ -768,9 +776,7 @@ export default class ChainService extends BaseService<Events> {
   private async loadRecentAssetTransfers(
     addressNetwork: AddressOnNetwork
   ): Promise<void> {
-    const blockHeight =
-      (await this.getBlockHeight(addressNetwork.network)) -
-      BLOCKS_TO_SKIP_FOR_TRANSACTION_HISTORY
```
Comment (Shadowfiend) [inline background/services/chain/index.ts:773]: This is important, and leaving it off will likely result in errors. See the comment for `BLOCKS_TO_SKIP_FOR_TRANSACTION_HISTORY`. The nodes will throw 500s if the requested block is too close.

This is also a reasonable flag in terms of trying to use this to fix very recent asset transfer lookups—we would need to wait ~20 blocks ~= 5 minutes before picking stuff up this way unfortunately.

File: background/lib/alchemy.ts [hunk 2]
```diff
@@ -51,13 +51,13 @@ export async function getAssetTransfers(
...
   // https://docs.alchemy.com/alchemy/enhanced-apis/transfers-api#alchemy_getassettransfers-ethereum-mainnet
-  let category = ["external", "internal", "token"]
+  let category = ["external", "internal", "erc20"]
 
   if (addressOnNetwork.network.name !== "Ethereum") {
     // Unfortunately even though "token" is supposed the default category for this API call - if the `category` property is omitted
     // the api returns an error about the category "iternal" not being supported
     // https://docs.alchemy.com/alchemy/enhanced-apis/transfers-api#alchemy_getassettransfers-testnets-and-layer-2s
-    category = ["token"]
+    category = ["erc20"]
```
Comment (0xDaedalus) [inline background/lib/alchemy.ts:60]: Neat!!  This is a very recent update to the alchemy api.  Lets add "external" here as well because it seems they support it now too.

File: background/services/doggo/index.ts [hunk 3]
```diff
@@ -59,30 +60,32 @@ export default class DoggoService extends BaseService<Events> {
...
-    })
-
-    // Track referrals for all added accounts and any new ones that are added
-    // after load.
-    this.chainService.emitter.on("newAccountToTrack", (addressOnNetwork) => {
-      this.trackReferrals(addressOnNetwork)
-    })
-    ;(await this.chainService.getAccountsToTrack()).forEach(
-      (addressOnNetwork) => {
+    if (!HIDE_TOKEN_FEATURES) {
```
Comment (0xDaedalus) [inline background/services/doggo/index.ts:63]: 👏

File: background/lib/alchemy.ts [hunk 4]
```diff
@@ -108,7 +108,7 @@ export async function getAssetTransfers(
         return null
       }
 
-      const asset = !transfer.rawContract.address
+      const asset = transfer.rawContract.address
```
Comment (greg-nagy) [inline background/lib/alchemy.ts:111]: This sneaky little fella ...

Comment (mhluongo) [reply background/lib/alchemy.ts:110]: 🎉🎉🎉

**Comment by mhluongo** [comment]
So now that we've fixed the asset discovery here... it's making all the terrible spam tokens show up in my wallet! We should probably only add these assets **if and only if** the `from` is us, otherwise anyone can aidrdop scam tokens on us without much recourse.

**Comment by mhluongo** [comment]
Eh, but that doesn't cover eg sending a token from another wallet of yours. Damn. I suppose we'll just need to double-down on metadata and the trusted / untrusted token UI

**Comment by henryboldi** [comment]
Perhaps can exclude aidrdop scam tokens by checking the price?

**Comment by mhluongo** [comment]
Unfortunately, that would also exclude LP tokens and other new stuff.

**Comment by Shadowfiend** [comment]
If there's a way to do it cleanly, we should probably only add tokens from asset transfers that are already in the token list until we can add a better UI for managing a denylist and trusted/untrusted stuff.

**Comment by Shadowfiend** [comment]
(Notably that limitation should ideally not exist for transactions that are not explicitly from our address.)

**Comment by mhluongo** [comment]
I think we should stick with what we have for now and solve the real problem of trust. Looking at my wallet, there are some good tokens in there that will never be in a token list... but that I want to add to my own internal list. Better to show those *and* the spam for a short while I think, and solve auto-discovered tokens ASAP.
