### PR TITLE
Enrichment Interaction: Annotate "to" address on transactions, not "from"

### LINKED ISSUE #2131: "Interacting With" address is wrong when confirming in-app swap
image

### PR DESCRIPTION
**Pull request by mhluongo**
Pretty sure wallet users know enough about their own wallet 😀

# To Test

- [ ] Try to swap from a wallet with an ENS or UNS name on mainnet
- [ ] In the confirmation page, the "Interacting with" field should be "Ox Router", rather than the wallet's ENS or UNS name

Closes #2131

### CODE REVIEW

File: background/services/enrichment/transactions.ts [hunk 1]
```diff
@@ -209,149 +205,164 @@ export default async function resolveTransactionAnnotation(
...
+      typeof transaction.input === "undefined"
     ) {
-      const [sender, recipient] = await Promise.all([
+      // If the tx has no data, it's either a simple ETH send, or it's relying
+      // on a contract that's `payable` to execute code
+
+      const [recipient, sender] = await Promise.all([
         enrichAddressOnNetwork(chainService, nameService, {
-          address: erc20Tx.args.from ?? transaction.from,
+          address: transaction.to,
```
Comment (hyphenized) [inline background/services/enrichment/transactions.ts:230]: Can we reuse the enriched address result from line 214 here? 👀

Comment (mhluongo) [reply background/services/enrichment/transactions.ts:230]: Looks like it!

**Review by 0xDaedalus — APPROVED** [review]
👑
