### PR TITLE
Fix sign data displayed message

### LINKED ISSUE #1590: Some weird looking message when signing a transaction on utopialabs.com icw Ledger. Transaction also fails
### **Build Info:**
0.13.17

### **Reproduction Steps:**

1. Sign transaction on utopialabs.com  icw Ledger

### **Expected Result:**

https://user-images.githubusercontent.com/103908695/172630926-dfd98a1b-2886-41c5-aee5-6fce58dfaaba.mov

### **Actual Result:**

https://user-images.githubusercontent.com/103908695/172630967-038f325d-7a57-4348-869d-19d3adc4f642.mov

### PR DESCRIPTION
**Pull request by jagodarybacka**
Resolves #1590

### What
Some dApps are sending sign data in plain text, not hex as expected. We should check if a sign message input is actually in hex format before decoding.

### Testing
Try to sign EIP191 message - for example, sign in to https://passport.gitcoin.co/#/

### CODE REVIEW

File: background/services/internal-ethereum-provider/index.ts [hunk 1]
```diff
@@ -355,15 +355,15 @@ export default class InternalEthereumProviderService extends BaseService<Events>
...
       account,
     }: {
-      hexData: string
+      input: string
       account: string
     },
     origin: string
   ) {
-    const asciiData = hexToAscii(hexData)
+    const asciiData = input.startsWith("0x") ? hexToAscii(input) : input
```
Comment (Shadowfiend) [inline background/services/internal-ethereum-provider/index.ts:366]: A small note for cleanup: we should replace `hexToAscii` everywhere with the Ethers [`toUtf8String`](https://docs.ethers.io/v5/api/utils/strings/#utils-toUtf8String). All else aside, `hexToAscii` is misnamed since it handles all UTF-8 codepoints rather than just ASCII :grimacing:
