### PR TITLE
📜 Fix scroll in core page which fixes overview tab

### LINKED ISSUE #1362: Overview not showing all Assets
### **Build Info:**
Build #2881

### **Reproduction Steps:**

1.  Have multiple Assets (10 + ?)
2.  View "Overview"
3.  View "Wallet"

### **Expected Result:**
All Assets should be present

### **Actual Result:**
Missing one Asset. In this case it's "APE" not showing in "Overview" but is showing in "Wallet"

See Video: https://www.awesomescreenshot.com/video/8606435?key=66efef7bec8ad7574b6f0571928757ba

### PR DESCRIPTION
**Pull request by henryboldi**
Turns out the missing asset on the overview tab was just hidden behind the tab
bar basically.  The height on the content area only adjusted to having a top
bar or not w/ a tab bar, but didn't handle a tab bar w/o the top bar. This PR
solves the issue by passing the bar settings into the core page component to
set the styles.

overview

Closes #1362

🤘

### CODE REVIEW

File: ui/components/Core/CorePage.tsx [hunk 1]
```diff
@@ -25,7 +36,7 @@ export default function CorePage(props: Props): ReactElement {
             align-items: center;
             background-color: var(--hunter-green);
             z-index: 10;
-            height: ${hasTopBar ? "480px" : "100vh"};
+            height: calc(100vh - ${barSpace}px);
```
Comment (jagodarybacka) [inline ui/components/Core/CorePage.tsx:39]: I would do it inline but it's up to you 
```suggestion
            height: calc(
              100vh - ${(hasTabBar ? 56 : 0) + (hasTopBar ? 64 : 0)}px
            );
```

**Review by jagodarybacka — APPROVED** [review]
Lookin good 💖 Let me know if you would like to refactor it
