### PR TITLE
👽  First Contact: Fix keep integration and onboard connect

### LINKED ISSUE #612: [Bug]: Dapp connections - onboard.js 'dismiss' window stays up until hard refresh
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I connect to yearn and curve (both use onboard JS!), after connecting I expect the 'dismiss' window to go away ... 

### What did not work?

... but it stays up until I do a hard refresh! After that the app loads correctly.

(here I hard refresh around 28 secs:)

https://user-images.githubusercontent.com/7005061/145902929-4fe41332-2c13-4253-8145-351c62b06466.mov

(here I hard refresh around 20 secs)

https://user-images.githubusercontent.com/7005061/145902932-fe26eb39-3b39-42ae-b429-417d247b4858.mov

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by greg-nagy**
Closes #612 

This also fixes the keep integration PR 

CleanShot 2021-12-16 at 22 53 13
CleanShot 2021-12-16 at 22 55 38

### CODE REVIEW

File: window-provider/index.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ import { EventEmitter } from "events"
 export default class TallyWindowProvider extends EventEmitter {
   // TODO: This should come from the background with onConnect when any interaction is initiated by the dApp.
   // onboard.js relies on this, or uses a deprecated api. It seemed to be a reasonable workaround for now.
-  chainId: number | undefined = 1
+  chainId = "0x1"
```
Comment (mhluongo) [inline window-provider/index.ts:19]: Good practice to keep hex length divisible by 2 for some dumb parsers.... no big deal here though

**Review by mhluongo — APPROVED** [review]
Tested and it works on Yearn and Uniswap. Didn't test against Keep or Saddle. Note that disconnecting doesn't appear to be making it to the dApps until a refresh.
