### PR TITLE
Navi-gation: Add default names and avatars

### LINKED ISSUE #468: Avatars
We only need a handful, which will be autoassigned whenever a user creates an account

### LINKED ISSUE #582: [Bug]: Accounts menu cleanup
### Discord Discussion Link

_No response_

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

1 - "Read-only mode" => "Read-only"
2 - Are we missing an icon next to "imported"? Design @ https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD?node-id=3584:151367#132443544 cc @VladUXUI 

Screen Shot 2021-12-11 at 5 06 15 PM

### Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Shadowfiend**
Because [Na'vi](https://en.wikipedia.org/wiki/Avatar_(2009_film)#Na'vi), hyuk hyuk.

Also fixes the imported icon. The fun has arrived.

-----

Fixes #582, fixes #468.

### CODE REVIEW

File: background/redux-slices/accounts.ts [hunk 1]
```diff
@@ -66,23 +79,46 @@ export const initialState = {
...
 
-function newAccountData(address: HexString, network: Network): AccountData {
+function newAccountData(
+  address: HexString,
+  network: Network,
+  existingAccountsCount: number
+): AccountData {
+  const accountNameDefault =
+    availableDefaultNames[
+      // Don't reuse names unless we absolutely have to.
```
Comment (mhluongo) [inline background/redux-slices/accounts.ts:89]: Is this comment accurate? We aren't tightly packing here, it's deterministic as a function of just the address, yeah?

Comment (mhluongo) [reply background/redux-slices/accounts.ts:89]: Ah yep we're packing. Alrighty.

**Review by mhluongo — APPROVED** [review]
Appears to work well imported and read-only wallets, and doesn't break with ENS names with or without an avatar. Let's do this
